export {default as GiftsGiftIcon} from '../assets/icons/gifts-gift-svgrepo-com.png';
export {default as LoudSpeakerIcon} from '../assets/icons/loudspeaker-svgrepo-com.png';
export {default as UserIcon} from '../assets/icons/user-svgrepo-com.png';
export {default as StarsStarIcon} from '../assets/icons/stars-star-svgrepo-com.png';
export {default as FireIcon} from '../assets/icons/fire-svgrepo-com.png';
export {default as SleepingStudentIcon} from '../assets/icons/student-sleeping-in-class-svgrepo-com.png';
export {default as PiggyBankIcon} from '../assets/icons/piggy-bank-save-svgrepo-com.png';
export {default as GraduationHatIcon} from '../assets/icons/hat-graduation-svgrepo-com.png';
export {default as MobilePhoneIcon} from '../assets/icons/mobile-phone-svgrepo-com.png';
export {default as GoogleIcon} from '../assets/icons/google-color-svgrepo-com.png';
export {default as FacebookIcon} from '../assets/icons/facebook-2-logo-svgrepo-com.png';
export {default as PersonProtectionIcon} from '../assets/icons/person-protection-security-svgrepo-com.png';
export {default as MoneyIcon} from '../assets/icons/money-svgrepo-com.png';
export {default as TelephoneIcon} from '../assets/icons/telephone-call-svgrepo-com.png';
export {default as ExploreIcon} from '../assets/icons/explore-solid-svgrepo-com.png';
export {default as ShareIcon} from '../assets/icons/share-svgrepo-com.png';
export {default as CouponIcon} from '../assets/icons/coupon-svgrepo-com.png';
export {default as AdvertisingSpeakerIcon} from '../assets/icons/advertising-speaker-svgrepo-com.png';
export {default as ChecklistIcon} from '../assets/icons/checklist-svgrepo-com.png';
export {default as ChevronRankIcon} from '../assets/icons/chevron-rank-svgrepo-com.png';
export {default as HourGlassNotDoneIcon} from '../assets/icons/hourglass-not-done-svgrepo-com.png';
export {default as StopwatchIcon} from '../assets/icons/stopwatch-svgrepo-com.png';
export {default as TelephoneCallIcon} from '../assets/icons/telephone-call-svgrepo-com.png';
export {default as WritingEducationLearningPencil} from '../assets/icons/writing-education-learning-pencil-note-write-svgrepo-com.png';
export const VinayakAvatarImage = 'https://avatars.githubusercontent.com/u/116362049?v=4';
export const InfiniteStarsBackgroundImage = 'https://th.bing.com/th/id/OIP.GJF9rzBd6QqXqicH9Mw06wHaEA?rs=1&pid=ImgDetMain';
